-- require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvimtree")
-- require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
-- require("core.plugin_config.lsp_config")
require("core.plugin_config.lsp_zero")
-- require("core.plugin_config.rust-tools")
require("core.plugin_config.neotest")
require("core.plugin_config.rustaceanvim")
